--- 
script: 
- vendor/bin/phpunit -c phpunit.travis.xml --testsuite="vfall"
language: php
env: 
  global: 
    secure: |-
      ytyMocwwZYL2tdN3xCgALO8TXsJZDzUy7DrnuQhh9BioJVdQGZNoaaZ4UMa8
      jbTEOSOrDeBZZF5FuJod+kic9zzM0Ai3SNPX6O0eIeWTUeFzGEZHzOyc8yO9
      Dv3ldB6Aas6wG/GLMd5ZiLAFcF/JuUmxxY9H5I6ZjdJwR1xiy38=
before_script: 
- mysql -e 'create database vf_magento'
- cd app/code/local/Elite
- curl -s http://getcomposer.org/installer | php -- --quiet
- php composer.phar install --dev
- cp Vaf/config.default.ini Vaf/config.ini
- mkdir -p vendor/kylecannon/magento/app/design/frontend/blank/default/template
- cd vendor/kylecannon/magento/app/design/frontend/blank/default/template
- ln -s ../../../../../../../../../../../../design/frontend/blank/default/template/vf vf
- cd ../../../../adminhtml/default/default/template/
- ln -s ../../../../../../../../../../../../design/adminhtml/default/default/template/vf vf
- cd ../../../../../../../../../
services: 
- mysql
php: 
- 5.3
- 5.4
